version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade --force-reinstall "botocore>1.21.30" "boto3>1.18.30" "awscli>1.20.30"

  build:
    commands:
      - echo "MODEL_EXECUTION_ROLE_ARN: $MODEL_EXECUTION_ROLE_ARN"
      - echo "SOURCE_MODEL_PACKAGE_GROUP_NAME: $SOURCE_MODEL_PACKAGE_GROUP_NAME"
      - echo "ARTIFACT_BUCKET: $ARTIFACT_BUCKET"
      - echo "EXPORT_TEMPLATE_NAME: $EXPORT_TEMPLATE_NAME"
      - python build.py --model-execution-role "$MODEL_EXECUTION_ROLE_ARN" --model-package-group-name "$SOURCE_MODEL_PACKAGE_GROUP_NAME" --s3-bucket "$ARTIFACT_BUCKET"
      - aws cloudformation package --template-file endpoint-config-template.yml --s3-bucket $ARTIFACT_BUCKET --output-template-file $EXPORT_TEMPLATE_NAME
      - cat $EXPORT_TEMPLATE_NAME

artifacts:
  files:
    - $EXPORT_TEMPLATE_NAME