version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - python -m src.pipeline.create
      - python -m src.pipeline.run

artifacts:
  files:
    - '**/*'